using System;

internal enum DebugWindowID
{
	STAGE_BLOCK_MANAGER,
	BLOCK_PATH_CONTROLLER,
	LEVEL_INFORMATION,
	PLAYER_INFORMATION,
	CAMERA_MANAGER,
	STAGE_DEBUG_INFORMATION,
	STAGE_DEBUG_INFORMATION2,
	STAGE_DEBUG_EDIT,
	MENU_DEBUG,
	STAGE_ITEM_MANAGER = 32768,
	SOUND_TEST_START
}
