using System;

public enum ObjectPartType
{
	BROKENBONUS_RATIO,
	BROKENBONUS_SUPER_RING,
	BROKENBONUS_REDSTAR_RING,
	BROKENBONUS_CRYSTAL10,
	COMBOBONUS_COMBO1,
	COMBOBONUS_COMBO2,
	COMBOBONUS_COMBO3,
	COMBOBONUS_COMBO4,
	COMBOBONUS_COMBO5,
	COMBOBONUS_COMBO6,
	COMBOBONUS_COMBO7,
	COMBOBONUS_BONUS1,
	COMBOBONUS_BONUS2,
	COMBOBONUS_BONUS3,
	COMBOBONUS_BONUS4,
	COMBOBONUS_BONUS5,
	COMBOBONUS_BONUS6,
	COMBOBONUS_BONUS7,
	COMBOBONUS_BONUS8,
	NUM,
	BROKENBONUS_ITEM_START = 1,
	BROKENBONUS_ITEM_END = 4,
	COMBOBONUS_ITEM_START = 4,
	COMBOBONUS_ITEM_END = 19
}
