using System;

public enum RewardType
{
	NONE = -1,
	ITEM_INVINCIBLE,
	ITEM_BARRIER,
	ITEM_MAGNET,
	ITEM_TRAMPOLINE,
	ITEM_COMBO,
	ITEM_LASER,
	ITEM_DRILL,
	ITEM_ASTEROID,
	RING,
	RSRING,
	MISSION_INCENTIVE_COUNT,
	ITEM_ROULETTE_PRIZE_COUNT = 10,
	CHARA_BEGIN = 300000,
	CHAO_BEGIN = 400000,
	ENERGY = 920000,
	SPECIAL_EGG = 220000
}
